### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Princesseuh** [bruits/maudit#1]
Welcome to the Maudit roadmap! Until needs arise for a more structured roadmap, this issue will serve as a non-exhaustive list of things I'm planning to do. 

Suggestions and contributions of things outside of this list are totally okay, and encouraged! Contributions for things in this list are also much welcome. For bugs, please submit issues.

## Current (0.10.0)

- [x] Built-in prefetch
- [x] Redirect primitives
- [ ] Improve documentation (website and docs.rs)

## Future

Unorganized grab bag of future ideas, some of these things will happen soon, some might not happen, or will happen only in a long time.

- [ ] Evaluate atomic builds
- [ ] Built-in fonts utilities
- [ ] Built-in SVG icons utilities
- [ ] Automatic head ordering
- [ ] PWA generation support
- [ ] Optional adapters for different deployment targets

## Previous versions

<details><summary>0.1.0</summary>

- [x] Static Routes
- [x] Endpoints Routes
</details>

<details><summary>0.2.0</summary>

- [x] Dynamic Routes
- [x] Ergonomic params (Allow user to cast from FxHashMap to typed params)
- [x] Type safe links
- [x] Images
- [x] Bundled scripts
- [x] Bundled CSS
	- [x] Tailwind
- [x] Metainfo about build
- [x] Pretty logging
- [x] Internal HTML post-processing step
- [x] Markdown
- [x] Build options (custom dist dir, etc)
- [x] Allow using other templating libraries than Maud (but keep it Maud-first)
- [x] Basic error handling
- [x] Website
- [x] Documentation
- [x] CLI
	- [x] Dev server
	- [x] Preview server
- [x] ToC generation
</details>

<details><summary>0.3.0</summary>

- [x] Explore how RenderResult interacts with encoding
- [x] Asset fingerprinting + proper hashing
- [x] 404 Route
- [x] Figure out assets in Markdown

### CLI

- [x] Dev should build the project first without needing a change
- [x] Project scaffolding
- [x] Build
- [x] Handle incrementing port when desired port is already used
- [x] Improving logging of the Preview server to be like dev

### Markdown Improvements

- [x] IDs on headings
- [x] Syntax Highlighting
- [x] Components in Markdown
	
## Infra
- [x] Unit Tests
- [x] Benchmarks
</details>

<details><summary>0.4.0</summary>

- [x] Return props from dynamic routes
- [x] Image processing
	- [x] Placeholder generation

</details>

<details><summary>0.5.0 & 0.6.0</summary>

- [x] Better error handling all around
- [x] Markdown shortcodes
- [x] Improve ergonomic around MarkdownOptions
- [x] Improve dev server stability

## Website

- [x] Blog
- [x] Contribute page
- [x] Mobile styling

</details>

<details><summary>0.7.0</summary>

- [x] Add initial support for i18n through page variants

</details>

<details><summary>0.8.0 & 0.9.0</summary>

- [x] Automatic sitemap generation

</details>
